version: "3.8"

services:
  api-prod:
    build:
        context: .
        dockerfile: Dockerfile
        target: prod
    platform: linux/x86_64
    image: asia-northeast1-docker.pkg.dev/labeling-tool-api/labeling-tool-api/backend-api